#include <iostream>
#include "counter.h"


/*
    ESTE ARCHIVO PRUEBA UNA CLASE LLAMADA Counter QUE HA SIDO 
    IMPLEMENTANDA  USANDO initializer list Y PASANDO UN 
    PARAMETRO COMO INICIALIZADOR Y NO UN LITERAL,
    YA QUE NO SABEMOS CUAL VLOR ASIGNARA 

    EN LA CLASE COUNTER SE DEBE USAR ESTE TIPO DE INICIALIZADOR 
    POR QUE LA VARIABLE maximum SE HA MARCADO COMO const ASI QUE
    NO LA PODEMOS INICIALIZAR EN EL CONSTRUCTOR Y TAMPOCO CONOCEMOS 
    EL VALOR CON EL QUE SERA INICIALIZADA.
*/

int main() {
    std::cout<< "probando counter" << std::endl;
    Counter ct(10);

    return 0;
}